name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    # Use the latest Ubuntu runner instead of the deprecated 20.04
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        # Only build for amd64 to ensure compatibility with SQLite and older CGO versions
        include:
          - goos: linux
            ext: ""
          - goos: darwin
            ext: ""
          - goos: windows
            ext: ".exe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Set up Docker Buildx
        if: matrix.goos == 'linux'
        uses: docker/setup-buildx-action@v3

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
          # Set CGO_ENABLED=1 for SQLite support
          CGO_ENABLED: 1
        run: |
          if [ "${{ matrix.goos }}" = "linux" ]; then
            # For Linux, use Docker with Debian Buster (older distro) to create a more compatible binary
            # Create a Dockerfile for building
            cat > Dockerfile.build << 'EOF'
            FROM debian:buster
            
            # Install build essentials and Go
            RUN apt-get update && apt-get install -y \
                build-essential \
                wget \
                git \
                ca-certificates
            
            # Install Go 1.21
            RUN wget -q https://go.dev/dl/go1.21.0.linux-amd64.tar.gz && \
                tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz && \
                rm go1.21.0.linux-amd64.tar.gz
            
            ENV PATH="/usr/local/go/bin:${PATH}"
            ENV CGO_ENABLED=1
            
            # Set working directory
            WORKDIR /build
            
            # Copy the source code
            COPY . .
            
            # Build with static linking for maximum compatibility
            RUN cd cmd/s3usage && go build -v -ldflags="-linkmode external -extldflags '-static'" -o /s3usage
            EOF
            
            # Build using Docker
            docker build -t s3usage-builder -f Dockerfile.build .
            
            # Extract the binary from the container
            docker create --name s3usage-extract s3usage-builder
            docker cp s3usage-extract:/s3usage "s3usage-${{ matrix.goos }}-amd64${{ matrix.ext }}"
            docker rm s3usage-extract
            
            # Ensure binary is executable
            chmod +x "s3usage-${{ matrix.goos }}-amd64${{ matrix.ext }}"
            
          elif [ "${{ matrix.goos }}" = "darwin" ]; then
            # For macOS, disable CGO as cross-compilation with CGO is problematic
            CGO_ENABLED=0 go build -v -o "s3usage-${{ matrix.goos }}-amd64${{ matrix.ext }}" ./cmd/s3usage
          else
            # For Windows, disable CGO as cross-compilation with CGO is problematic
            CGO_ENABLED=0 go build -v -o "s3usage-${{ matrix.goos }}-amd64${{ matrix.ext }}" ./cmd/s3usage
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3usage-${{ matrix.goos }}-amd64
          path: s3usage-${{ matrix.goos }}-amd64${{ matrix.ext }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          pattern: s3usage-*
          merge-multiple: true

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
          draft: false
          prerelease: false
          generate_release_notes: true 